[phases.setup]
nixPkgs = ["nodejs", "python39", "postgresql"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "docker-compose up -d"

