"""Parametrizable system with custom fields

Revision ID: 156f853a970e
Revises: 91e2c5457d59
Create Date: 2025-09-16 03:40:07.887504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '156f853a970e'
down_revision = '91e2c5457d59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('custom_fields_config', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('custom_fields', sa.JSON(), nullable=True))
    op.drop_column('tasks', 'eis')
    op.drop_column('tasks', 'horas_pendientes')
    op.drop_column('tasks', 'asesor')
    op.drop_column('tasks', 'programa')
    op.drop_column('tasks', 'no_aut')
    op.drop_column('tasks', 'codigo')
    op.drop_column('tasks', 'estado_detallado')
    op.drop_column('tasks', 'fecha_final')
    op.drop_column('tasks', 'fecha_asignacion')
    op.drop_column('tasks', 'observaciones')
    op.drop_column('tasks', 'asesor_asignado')
    op.drop_column('tasks', 'nit')
    op.drop_column('tasks', 'entregables')
    op.drop_column('tasks', 'id_actividad')
    op.drop_column('tasks', 'pendientes_registrar_app')
    op.drop_column('tasks', 'nro_os')
    op.drop_column('tasks', 'fecha_autorizacion')
    op.drop_column('tasks', 'fecha_maxima_ejecucion')
    op.drop_column('tasks', 'componente')
    op.drop_column('tasks', 'detalle_actividad')
    op.drop_column('tasks', 'horas_asignadas')
    op.drop_column('tasks', 'tipo_actividad')
    op.drop_column('tasks', 'dis_responsable')
    op.drop_column('tasks', 'mes')
    op.drop_column('tasks', 'actividad')
    op.drop_column('tasks', 'linea')
    op.drop_column('tasks', 'ciudad_desarrollo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('ciudad_desarrollo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('linea', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('actividad', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('mes', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('dis_responsable', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('tipo_actividad', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('horas_asignadas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('detalle_actividad', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('componente', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('fecha_maxima_ejecucion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('fecha_autorizacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('nro_os', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('pendientes_registrar_app', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('id_actividad', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('entregables', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('nit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('asesor_asignado', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('fecha_asignacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('fecha_final', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('estado_detallado', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('no_aut', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('programa', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('asesor', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('horas_pendientes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('eis', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'custom_fields')
    op.drop_column('companies', 'custom_fields_config')
    # ### end Alembic commands ###
