"""Add Excel fields to tasks

Revision ID: 91e2c5457d59
Revises: 
Create Date: 2025-09-16 03:32:57.433091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e2c5457d59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('nit', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('linea', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('programa', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('componente', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('actividad', sa.String(length=200), nullable=True))
    op.add_column('tasks', sa.Column('ciudad_desarrollo', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('detalle_actividad', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('entregables', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('tipo_actividad', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('nro_os', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('fecha_final', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('horas_asignadas', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('horas_pendientes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('dis_responsable', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('asesor_asignado', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('fecha_asignacion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('observaciones', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('codigo', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('no_aut', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('id_actividad', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('fecha_autorizacion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('fecha_maxima_ejecucion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('mes', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('pendientes_registrar_app', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('eis', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('asesor', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('estado_detallado', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'estado_detallado')
    op.drop_column('tasks', 'asesor')
    op.drop_column('tasks', 'eis')
    op.drop_column('tasks', 'pendientes_registrar_app')
    op.drop_column('tasks', 'mes')
    op.drop_column('tasks', 'fecha_maxima_ejecucion')
    op.drop_column('tasks', 'fecha_autorizacion')
    op.drop_column('tasks', 'id_actividad')
    op.drop_column('tasks', 'no_aut')
    op.drop_column('tasks', 'codigo')
    op.drop_column('tasks', 'observaciones')
    op.drop_column('tasks', 'fecha_asignacion')
    op.drop_column('tasks', 'asesor_asignado')
    op.drop_column('tasks', 'dis_responsable')
    op.drop_column('tasks', 'horas_pendientes')
    op.drop_column('tasks', 'horas_asignadas')
    op.drop_column('tasks', 'fecha_final')
    op.drop_column('tasks', 'nro_os')
    op.drop_column('tasks', 'tipo_actividad')
    op.drop_column('tasks', 'entregables')
    op.drop_column('tasks', 'detalle_actividad')
    op.drop_column('tasks', 'ciudad_desarrollo')
    op.drop_column('tasks', 'actividad')
    op.drop_column('tasks', 'componente')
    op.drop_column('tasks', 'programa')
    op.drop_column('tasks', 'linea')
    op.drop_column('tasks', 'nit')
    # ### end Alembic commands ###
